/**
 * Known form-wording → structuredFields keys.
 * Add phrases here as new sites show up; keep them lowercase, punctuation-free
 * (matcher normalizes the same way). Longer phrases are tried first.
 */

export type StructuredMatchKey =
  | 'fullName'
  | 'email'
  | 'phone'
  | 'address.street'
  | 'address.city'
  | 'address.stateProvince'
  | 'address.postalCode'
  | 'address.country'
  | 'linkedinUrl'
  | 'portfolioUrl'
  | 'workAuthorization'
  | 'yearsExperience'
  | 'salaryExpectation'
  | 'noticePeriod'
  | 'dateOfBirth'

export const FIELD_SYNONYMS: Record<StructuredMatchKey, readonly string[]> = {
  fullName: [
    'full legal name',
    'full name',
    'legal name',
    'complete name',
    'applicant name',
    'candidate name',
    'your name',
    'official name',
    'name as on id',
    'name as it appears',
    'employee name',
  ],
  email: [
    'email address',
    'e mail address',
    'electronic mail',
    'email id',
    'emailid',
    'work email',
    'personal email',
    'contact email',
    'applicant email',
    'primary email',
    'preferred email',
    'your email',
    'e mail',
    'email',
    'mail',
  ],
  phone: [
    'phone number',
    'telephone number',
    'mobile number',
    'mobile phone',
    'cell phone',
    'cellphone',
    'contact number',
    'contact phone',
    'primary phone',
    'home phone',
    'work phone',
    'phone no',
    'tel no',
    'telephone',
    'mobile',
    'phone',
    'cell',
    'tel',
  ],
  'address.street': [
    'address line 1',
    'address line one',
    'address line1',
    'street address',
    'residential address',
    'physical address',
    'mailing address',
    'home address',
    'house address',
    'street name',
    'address street',
    'addr line 1',
    'address1',
    'addr1',
    'line 1',
    'street',
    'address',
  ],
  'address.city': [
    'city town',
    'town city',
    'city name',
    'municipality',
    'locality',
    'city',
    'town',
  ],
  'address.stateProvince': [
    'state or province',
    'state province',
    'province state',
    'state region',
    'prefecture',
    'province',
    'region',
    'state',
  ],
  'address.postalCode': [
    'postal code',
    'post code',
    'zip code',
    'pin code',
    'zipcode',
    'postcode',
    'pincode',
    'zip postal',
    'postal zip',
    'postal',
    'zip',
  ],
  'address.country': [
    'country of residence',
    'country or region',
    'country region',
    'residence country',
    'home country',
    'country',
    'nation',
  ],
  linkedinUrl: [
    'linkedin profile url',
    'linkedin profile',
    'linkedin url',
    'linkedin link',
    'linkedin address',
    'linkedin.com',
    'linked in',
    'linkedin',
  ],
  portfolioUrl: [
    'portfolio website',
    'online portfolio',
    'personal portfolio',
    'personal website',
    'personal webpage',
    'personal site',
    'personal url',
    'portfolio url',
    'portfolio link',
    'github profile',
    'github url',
    'website url',
    'web site',
    'home page',
    'homepage',
    'portfolio',
    'website',
    'github',
  ],
  workAuthorization: [
    'legally authorized to work',
    'legally authorised to work',
    'authorized to work',
    'authorised to work',
    'do you require sponsorship',
    'will you need sponsorship',
    'require sponsorship',
    'needs sponsorship',
    'need visa sponsorship',
    'visa sponsorship',
    'sponsorship required',
    'employment authorization',
    'work authorization',
    'work authorisation',
    'work eligibility',
    'eligible to work',
    'right to work',
    'work permit',
    'visa status',
    'work visa',
  ],
  yearsExperience: [
    'years of relevant experience',
    'years of work experience',
    'years of experience',
    'work experience years',
    'number of years experience',
    'relevant experience years',
    'years experience',
    'total experience',
    'years working',
    'how many years',
    'total years',
    'experience years',
    'yoe',
  ],
  salaryExpectation: [
    'salary expectation',
    'expected compensation',
    'compensation expectation',
    'compensation requirements',
    'salary requirements',
    'expected salary',
    'desired salary',
    'desired compensation',
    'desired pay',
    'expected pay',
    'pay expectation',
    'salary range',
    'expected ctc',
    'desired ctc',
    'annual salary expectation',
    'salary expected',
    'salary',
  ],
  noticePeriod: [
    'when can you start',
    'how soon can you start',
    'earliest start date',
    'available to start',
    'start date availability',
    'earliest start',
    'notice period',
    'joining time',
    'time to join',
    'weeks notice',
    'notice days',
    'serving notice',
    'date available',
    'when available',
    'available from',
    'availability date',
    'availability',
    'notice',
  ],
  dateOfBirth: [
    'date of birth',
    'birth date',
    'birthdate',
    'birthday',
    'born on',
    'date born',
    'dob',
  ],
}

/** Phrases that mean this key should not match even if a synonym appears. */
export const FIELD_NEGATIVES: Partial<
  Record<StructuredMatchKey, readonly string[]>
> = {
  fullName: [
    'first name',
    'last name',
    'given name',
    'family name',
    'middle name',
    'maiden name',
    'user name',
    'username',
    'company name',
    'school name',
    'employer',
    'organization',
    'university',
    'college',
    'file name',
    'filename',
    'emergency',
    'reference',
    'parent',
    'guardian',
    'nickname',
    'surname',
    'team name',
  ],
  email: [
    'manager',
    'supervisor',
    'reference',
    'emergency',
    'parent',
    'recruiter',
    'referrer',
  ],
  phone: [
    'manager',
    'supervisor',
    'reference',
    'emergency',
    'parent',
    'fax',
  ],
  'address.street': ['line 2', 'line2', 'apt', 'suite', 'unit', 'birth'],
  'address.city': ['birth', 'emergency'],
  'address.stateProvince': ['statement', 'united states', 'status'],
  'address.country': ['citizenship', 'nationality', 'citizen', 'birth'],
  linkedinUrl: [],
  portfolioUrl: ['company website', 'employer', 'job posting', 'organization'],
  workAuthorization: [],
  yearsExperience: ['at company', 'with us', 'this role', 'age'],
  salaryExpectation: [
    'current salary',
    'present salary',
    'previous salary',
    'last salary',
    'last drawn',
  ],
  noticePeriod: ['relocate', 'travel', 'weekend', 'overtime', 'birth'],
  dateOfBirth: [
    'start date',
    'available',
    'graduation',
    'issued',
    'expiry',
    'expiration',
    'interview',
    'visa',
  ],
}
